# Generated by Django 5.1.6 on 2025-02-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0002_remove_usuario_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='certificaciones',
            field=models.FileField(blank=True, null=True, upload_to='certificaciones/'),
        ),
    ]
