# Generated by Django 5.1.6 on 2025-02-19 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0006_remove_servicio_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotizacion',
        ),
    ]
