# Generated by Django 5.1.6 on 2025-02-24 01:42

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0013_evaluacioncotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacioncotizacion',
            name='estimacion_costos',
        ),
        migrations.AddField(
            model_name='evaluacioncotizacion',
            name='fecha_servicio_programado',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha programada para realizar el servicio.'),
        ),
        migrations.AddField(
            model_name='evaluacioncotizacion',
            name='hora_servicio_programado',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Hora programada para realizar el servicio.'),
        ),
        migrations.AddField(
            model_name='evaluacioncotizacion',
            name='precio_desplazamiento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de desplazamiento.', max_digits=10),
        ),
        migrations.AddField(
            model_name='evaluacioncotizacion',
            name='precio_insumos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de los insumos.', max_digits=10),
        ),
        migrations.AddField(
            model_name='evaluacioncotizacion',
            name='precio_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de mano de obra.', max_digits=10),
        ),
        migrations.AddField(
            model_name='evaluacioncotizacion',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor total a pagar.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='evaluacioncotizacion',
            name='insumos',
            field=models.TextField(help_text='Descripción de los insumos necesarios.'),
        ),
        migrations.AlterField(
            model_name='evaluacioncotizacion',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones y comentarios técnicos.', null=True),
        ),
        migrations.AlterField(
            model_name='evaluacioncotizacion',
            name='tiempo_estimado',
            field=models.DecimalField(decimal_places=2, help_text='Tiempo estimado en horas.', max_digits=5),
        ),
    ]
